# Generated by Django 3.2.5 on 2021-07-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NightstandTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Шаблон тумби',
                'verbose_name_plural': 'Шаблони тумб',
            },
        ),
        migrations.CreateModel(
            name='NightstandInputItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Число, вимір в мм'), (2, 'Кількість'), (3, 'Проценти'), (4, 'Так/ні')])),
                ('default_value', models.IntegerField()),
                ('formula_name', models.CharField(max_length=50)),
                ('nightstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='constructor.nightstandtemplate')),
            ],
            options={
                'verbose_name': 'Шаблон вхідного параметру тумби',
                'verbose_name_plural': 'Шаблони вхідних параметрів тубми',
            },
        ),
        migrations.CreateModel(
            name='NightstandCalculatedItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base', models.CharField(choices=[('ДСП', 'Dsp'), ('ДВП', 'Dvp'), ('скло', 'Glass'), ('фасад', 'Door'), ('стільниця', 'Tabletop')], max_length=20)),
                ('width', models.CharField(blank=True, default='', max_length=255)),
                ('length', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.CharField(blank=True, default='', max_length=255)),
                ('square', models.CharField(blank=True, default='', max_length=255)),
                ('square_extra', models.CharField(blank=True, default='', max_length=255)),
                ('edge', models.CharField(blank=True, default='', max_length=255)),
                ('edge_extra', models.CharField(blank=True, default='', max_length=255)),
                ('drilling_count', models.CharField(blank=True, default='', max_length=255)),
                ('nightstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='constructor.nightstandtemplate')),
            ],
            options={
                'verbose_name': 'Шаблон розрахункового елемента',
                'verbose_name_plural': 'Шаблони разрахункових елементів',
            },
        ),
    ]
