# Generated by Django 3.2.5 on 2021-07-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nightstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nightstands', to='project.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.nightstandtemplate')),
            ],
            options={
                'verbose_name': 'Тумба',
                'verbose_name_plural': 'Тумби',
            },
        ),
        migrations.RenameField(
            model_name='nightstandcalculateditemtemplate',
            old_name='amount',
            new_name='amount_formula',
        ),
        migrations.RenameField(
            model_name='nightstandcalculateditemtemplate',
            old_name='drilling_count',
            new_name='drilling_count_formula',
        ),
        migrations.RenameField(
            model_name='nightstandcalculateditemtemplate',
            old_name='edge',
            new_name='edge_extra_formula',
        ),
        migrations.RenameField(
            model_name='nightstandcalculateditemtemplate',
            old_name='edge_extra',
            new_name='edge_formula',
        ),
        migrations.RenameField(
            model_name='nightstandcalculateditemtemplate',
            old_name='length',
            new_name='length_formula',
        ),
        migrations.RenameField(
            model_name='nightstandcalculateditemtemplate',
            old_name='square',
            new_name='square_extra_formula',
        ),
        migrations.RenameField(
            model_name='nightstandcalculateditemtemplate',
            old_name='square_extra',
            new_name='square_formula',
        ),
        migrations.RenameField(
            model_name='nightstandcalculateditemtemplate',
            old_name='width',
            new_name='width_formula',
        ),
        migrations.CreateModel(
            name='NightstandInputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('nightstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='constructor.nightstand')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.nightstandinputitemtemplate')),
            ],
            options={
                'verbose_name': 'Вхідний параметр тумби',
                'verbose_name_plural': 'Вхідні параметри тубми',
            },
        ),
        migrations.CreateModel(
            name='NightstandCalculatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('square', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('square_extra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('edge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('edge_extra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('drilling_count', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nightstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='constructor.nightstand')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.nightstandcalculateditemtemplate')),
            ],
            options={
                'verbose_name': 'Розрахунковий елемент',
                'verbose_name_plural': 'Розрахункові елементи',
            },
        ),
    ]
