# Generated by Django 3.2.5 on 2021-07-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_auto_20210724_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightstandcalculateditemtemplate',
            name='formula_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
