# Generated by Django 3.2.5 on 2021-07-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_nightstandcalculateditemtemplate_formula_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightstandtemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
