# Generated by Django 3.2.5 on 2021-09-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_nightstandtemplate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalInputValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('formula_name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Глобальна змінна',
                'verbose_name_plural': 'Глобальні змінні',
            },
        ),
        migrations.AlterModelOptions(
            name='nightstandcalculateditemtemplate',
            options={'verbose_name': 'Шаблон розрахункового елемента', 'verbose_name_plural': 'Шаблони розрахункових елементів'},
        ),
    ]
