# Generated by Django 3.2.5 on 2021-09-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_auto_20210921_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightstand',
            name='short_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nightstandcalculateditem',
            name='edited',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='nightstandtemplate',
            name='short_name_formula',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
