# Generated by Django 3.2.5 on 2021-09-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_auto_20210927_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightstand',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
