# Generated by Django 3.2.5 on 2021-09-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_alter_nightstand_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightstandcalculateditem',
            name='rotation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nightstandcalculateditemtemplate',
            name='rotation_formula',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
