# Generated by Django 3.2.5 on 2023-07-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(301, 'Каса'), (631, 'Рахунок контрагента')])),
            ],
            options={
                'verbose_name': 'Каса',
            },
        ),
        migrations.CreateModel(
            name='CounterParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Контрагент',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Прихідний касовий ордер від контрагента'), (2, 'Повернення готівки від підзвітної особи'), (3, 'Оплата контрагенту'), (4, 'Видача готівки підзвітній особі'), (5, 'Поверення готівки покупцеві')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('number', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('created', 'Створено'), ('accounted', 'Проведено'), ('canceled', 'Скасовано')], max_length=50)),
                ('note', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_documents', to='accounts.account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_documents', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='accounts.account')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.document')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Рух коштів',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='counter_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.counterparty'),
        ),
    ]
